### ISSUE TITLE
update to webpack 2

### ISSUE THREAD

**Issue by bradennapier** [NSLS/universal-webpack-boilerplate#1]
universal-webpack only supports webpack 2 now apparently and according to this package.json it is webpack 1.

**Comment by ignatevdev** [comment]
I will try to migrate this project to webpack 2 as soon as possible and will close the issue when it will be done. Thanks for informing me about that!

**Comment by bradennapier** [comment]
Awesome, thanks!!

**Comment by ignatevdev** [comment]
@bradennapier I have migrated this boilerplate to the newest version of universal-webpack and webpack itself and made some other changes which you can find in 1.0 version release. Feel free to test it and report any issues or suggestions you might come up with.
