### ISSUE TITLE
Where is webpack.dll.config.babel.js?

### ISSUE THREAD

**Issue by tearsofphoenix** [NSLS/universal-webpack-boilerplate#5]
Seems the project support webpack DLLPlugin, but where is the config?

**Comment by ignatevdev** [comment]
Hi.
This project used to have a DLLPlugin support with a separate config file, which you can find in the first versions, but after Webpack 2 has released, DLLPLugin was removed from the list of the official plugins, which you can find [here](https://webpack.js.org/plugins/), so I had to remove it when upgrading the project to Webpack 2.
